name: Check Reserved Keywords

on:
  - pull_request

jobs:
  check-reserved-keywords:
    name: Check Reserved Keywords
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v10
      with:
        python-version: 3.12

    - name: Install Dependencies
      run: uv sync --group dev

    - name: Check Keywords
      run: uv run make check_keywords
