db:
  image: mysql:5.6
  container_name: db
  environment:
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

memcache:
  image: memcached:1.4.24
  container_name: memcache

{{cookiecutter.repo_name}}:
  # Uncomment this line to use the official {{cookiecutter.repo_name}} base image
  image: openedx/{{cookiecutter.repo_name}}

  container_name: {{cookiecutter.repo_name}}
  volumes:
    - .:/edx/app/{{cookiecutter.repo_name}}/
  command: bash -c 'gunicorn --reload --workers=2 --name {{cookiecutter.repo_name}} -b :{{cookiecutter.port}} -c /edx/app/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}/docker_gunicorn_configuration.py --log-file - --max-requests=1000 {{cookiecutter.repo_name}}.wsgi:application'
  environment:
    DJANGO_SETTINGS_MODULE: {{cookiecutter.repo_name}}.settings.devstack
  ports:
    - "{{cookiecutter.port}}:{{cookiecutter.port}}" # TODO: change this to your port
