# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

# Set the version of python needed to build these docs.
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

python:
  install:
    - requirements: requirements/doc.txt

    # This will pip install this repo into the python environment
    # if you are using this in a repo that is not pip installable
    # then you should remove the following two lines.
    - method: pip
      path: .
