name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"

jobs:
  run_tests:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
        toxenv: ["py311", "quality", "docs", "pii_check"]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v10
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: uv run --group ci tox

      - name: Run coverage
        if: matrix.python-version == '3.12' && matrix.toxenv == 'py312'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: true
